package com.smarthome.entity;

public enum EventType {
    STATUS_CHANGE,
    SENSOR_READING,
    ALERT,
    ERROR,
    MAINTENANCE,
    FIRMWARE_UPDATE,
    BATTERY_LOW,
    CONNECTION_LOST,
    CONNECTION_RESTORED,
    USER_INTERACTION,
    AUTOMATION_TRIGGERED,
    ENERGY_CONSUMPTION,
    TEMPERATURE_CHANGE,
    HUMIDITY_CHANGE,
    MOTION_DETECTED,
    DOOR_OPENED,
    DOOR_CLOSED,
    LIGHT_ON,
    LIGHT_OFF,
    SECURITY_BREACH,
    SMOKE_DETECTED,
    WATER_LEAK_DETECTED
}
