package com.smarthome.entity;

public enum TriggerType {
    TIME_BASED,
    DEVICE_STATUS_CHANGE,
    SENSOR_THRESHOLD,
    MOTION_DETECTED,
    DOOR_OPENED,
    TEMPERATURE_ABOVE,
    TEMPERATURE_BELOW,
    HUMIDITY_ABOVE,
    HUMIDITY_BELOW,
    ENERGY_THRESHOLD,
    SUNRISE,
    SUNSET,
    LOCATION_BASED,
    MANUAL_TRIGGER,
    SCHEDULE,
    DEVICE_OFFLINE,
    DEVICE_ONLINE,
    BATTERY_LOW,
    SECURITY_BREACH,
    SMOKE_DETECTED,
    WATER_LEAK_DETECTED,
    POWER_OUTAGE,
    POWER_RESTORED
}
